name: fair-calibrate-v1.4-comparison
channels:
  - chrisroadmap
  - conda-forge
dependencies:
  - fair==2.1.3
  - h5py
  - jupyter
  - matplotlib
  - nbstripout
  - netCDF4
  - numpy
  - pandas
  - pooch
  - python-dotenv
  - scipy
  - scmdata
  - tqdm
  - xarray
  - pip
  - pip:
    - aneris-iamc[units]
